.gitignore, pyclam/manifold.py
=> brought in changes from anomaly experiments

pyclam/manifold.py
fix: points were being duplicated in partition
=> fixed duplicated points

.hooks/commit-msg, pyclam/manifold.py, pyclam/tests/test_cluster.py
feature: unified distance calls into single function
=> unified distance calls

Cargo.toml, pyclam/criterion.py, pyclam/datasets.py, pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_functional.py, pyclam/tests/test_graph.py, pyclam/tests/test_manifold.py
added edge-pruning and ignoring extra-vacuous edges.
=> added edge-pruniing

Cargo.toml, pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_graph.py
Implemented the basic outrank algorithm.
=> Basic outrank algorithm

pyclam/criterion.py, pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_criterion.py, pyclam/tests/test_functional.py, pyclam/tests/test_graph.py, pyclam/tests/test_manifold.py, pyclam/types.py
Let's look this over and maybe write more tests
=> almost done

pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_criterion.py, pyclam/tests/test_functional.py, pyclam/tests/test_graph.py, pyclam/tests/test_manifold.py, pyproject.toml
feat: extended graph-building to handle both optimal and layer graphs
perf: finding candidates is a lot faster
feat: added grace period of initial depth before marking optimal clusters
=> extended graph-building to handle both optimal and layer graphs

pyclam/criterion.py, pyclam/manifold.py, pyclam/tests/test_criterion.py
added ability to select clusters for optimal graph by using LR constants
=> SelectionClause for LR constants

Cargo.toml, pyclam/criterion.py, pyclam/manifold.py, pyclam/tests/test_criterion.py, pyclam/tests/test_functional.py, pyclam/tests/test_graph.py, pyclam/tests/test_manifold.py, pyproject.toml
Manifold now contains a graphs variable.
There is one graph per Selection Criterion provided for Manifild.build
=> added support for multiple graphs

Cargo.toml, pyclam/__init__.py, pyclam/chaoda.py, pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_criterion.py, pyclam/tests/test_functional.py, pyclam/tests/test_graph.py, pyclam/tests/test_manifold.py, pyclam/types.py, pyproject.toml
YAY! This was very fun to code up
=> Graph refactor and random-walks in chaoda

Cargo.toml, pyclam/chaoda.py, pyclam/manifold.py, pyproject.toml
feat: usage of new methods in CHAODA
We now sit on 6 CHAODA methods, potentially 7 after today's meeting.
Later, I might add a faster estimate for Graph.diameter
=> feat: eccentricity, diameter, and as-matrix methods in Graph

Cargo.toml, pyclam/chaoda.py, pyclam/manifold.py, pyclam/tests/utils.py, pyclam/utils.py, pyproject.toml
feat: broke out utils file for common usage
=> utils file for common functions and constants

Cargo.toml, README.md, pyclam/__init__.py, pyclam/chaoda.py, pyclam/criterion.py, pyclam/manifold.py, pyclam/search.py, pyclam/tests/test_cluster.py, pyclam/tests/test_functional.py, pyclam/tests/test_manifold.py, pyclam/tests/test_search.py, pyclam/tests/utils.py, pyclam/types.py, pyproject.toml
feat: integrated CHESS module, updated README
=> Creating a CHESS module, and updating the README

Cargo.toml, pyclam/manifold.py, pyclam/tests/test_graph.py, pyproject.toml
These methods will later be used to write dump/load methods for Graph.
feat: as-dot-string and from-dot-string methods for Graph
=> Dot-File functionality for Graph

Cargo.toml, pyclam/manifold.py, pyclam/tests/test_cluster.py, pyclam/tests/test_graph.py, pyproject.toml
The Jaccard index is going to be useful for thinking a bit differently about persistent components.
=> Jaccard Index methods for Cluster and Graph

Cargo.toml, pyclam/criterion.py, pyclam/tests/test_criterion.py, pyproject.toml
=> feat: Select graphs by property of cluster

Cargo.toml, pyclam/criterion.py, pyclam/tests/test_criterion.py, pyproject.toml
Selects clusters that have an overwhelming majority of points from one class.
feat: label based selection criteria
=> Added Labels as a Selection Criterion

Cargo.toml, pyclam/manifold.py, pyclam/utils.py, pyproject.toml
feat: normalize function now handles 1-d and 2-d arrays
=> added support for normalizing 2-d arrays

Cargo.toml, pyclam/criterion.py, pyclam/tests/test_criterion.py, pyproject.toml
Removed Linear Regression and Regression Tree specific Selection Criteria in favor of a single Criterion for meta-ml functions
=> New Selection criterion for using meta-ml methods

Cargo.toml, pyclam/manifold.py, pyclam/tests/test_graph.py, pyproject.toml
=> Added walkable_graph as a property in Graph

benches/search.rs, src/cluster.rs, src/criteria.rs, src/dataset.rs, src/graph.rs, src/lib.rs, src/manifold.rs, src/metric.rs, src/search.rs, src/utils.rs
Implemented dataset as a trait.
Also ran rustfmt
=> feat: dataset as a trait

poetry.lock, pyclam/chaoda.py, pyclam/criterion.py, pyclam/manifold.py, pyclam/search.py, pyproject.toml, requirements.txt
building graphs in .fit method instead.
fixed transition matrix.
removed random-walks and added vertex-degree.
cleaner meta-ml.select. method
faster edges-dict by iterating only once on edges.
updated dependency versions
added class variable of method names
using a criterion-function for each pair of metric/method
fix: now using method-graph pairs as well
fix: criterion.Layer usage in Search
=> review: changes after first round of review for paper

Cargo.toml
=> added benches back

src/anomaly/chaoda.rs, src/anomaly/individual_algorithms.rs, src/anomaly/meta_ml_functions.rs, src/core/cluster.rs, src/core/graph.rs, src/core/manifold.rs, src/main.rs, src/search/cakes.rs, src/traits/number.rs, src/utils/mod.rs, src/utils/readers.rs
Added minimal documentation for every(?) function/type used for anomaly detection. I will add more details to the docs after some code optimization.
=> Added missing documentation

Cargo.toml, pyclam/anomaly_detection/__init__.py, pyclam/anomaly_detection/meta_ml_models.py, pyclam/core/manifold.py
This adds training classes for Meta-ml models and logic for extracting python code from sklearn methods.
=> created classes for meta-ml models

src/distances/mod.rs, src/distances/strings.rs
Moved Levenshtein distance function over from distance crate. Altered function and  function signature to be consistent with existing edit distance function signatures.
=> Levenshtein

.github/workflows/benchmark.yml, .github/workflows/coverage.yml, .github/workflows/tests.yml
This PR removes the installation of hdf5 from automated github workflows.
=> removed hdf5 from workflows

examples/reports.rs, src/core/cluster.rs, src/core/cluster_criteria.rs, src/core/dataset.rs
Just come clippy things after the merging the branch from Oliver
=> minor cleanup

.bumpversion.cfg, README.md, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/core/cluster/_cluster.rs, abd-clam/src/lib.rs, abd-clam/src/utils.rs, py-clam/README.md, py-clam/abd_clam/__init__.py, py-clam/pyproject.toml, pyproject.toml
This PR brings back those cluster members and adds tests for them.
=> Bringing back arg-center and arg-radial

.bumpversion.cfg, README.md, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/cakes/knn/mod.rs, abd-clam/src/cakes/knn/repeated_rnn.rs, abd-clam/src/cakes/mod.rs, abd-clam/src/cakes/sharded.rs, abd-clam/src/lib.rs, py-clam/README.md, py-clam/abd_clam/__init__.py, py-clam/pyproject.toml, pyproject.toml
=> Moved ShardedCakes changes from other branch

.bumpversion.cfg, README.md, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/lib.rs, cakes-results/.gitignore, cakes-results/Cargo.toml, cakes-results/LICENSE, cakes-results/README.md, cakes-results/pyproject.toml, cakes-results/python/cakes_results/__init__.py, cakes-results/python/cakes_results/__main__.py, cakes-results/python/cakes_results/scaling_plots.py, cakes-results/src/ann_datasets.rs, cakes-results/src/knn_reports.rs, cakes-results/src/scaling_reports.rs, cakes-results/src/utils.rs, knn-benchmarks.sh, py-clam/README.md, py-clam/abd_clam/__init__.py, py-clam/pyproject.toml, pyproject.toml, scaling-benchmarks.sh
=> Added Binaries for reproducing results from the IEEE-2023 submission

.bumpversion.cfg, README.md, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/cakes/knn/greedy_sieve.rs, abd-clam/src/cakes/knn/mod.rs, abd-clam/src/cakes/knn/repeated_rnn.rs, abd-clam/src/cakes/knn/sieve.rs, abd-clam/src/cakes/knn/sieve_sep_center.rs, abd-clam/src/lib.rs, cakes-results/Cargo.toml, cakes-results/src/scaling_reports.rs, py-clam/README.md, py-clam/abd_clam/__init__.py, py-clam/pyproject.toml, pyproject.toml, scaling-benchmarks.sh
I will revisit the algorithms later for better fixes.
=> Added a bandaid for the panics in knn-search algorithm.

.bumpversion.cfg, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/benches/knn-search.rs, abd-clam/benches/knn-vs-rnn.rs, abd-clam/benches/rnn-search.rs, abd-clam/src/cakes/sharded.rs, abd-clam/src/lib.rs, abd-clam/tests/test_dataset.rs, abd-clam/tests/utils.rs, cakes-results/src/ann_datasets.rs
=> Updated dependencies for `distances` and `SyMaGen` crates

.bumpversion.cfg, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/core/cluster/_cluster.rs, abd-clam/src/core/cluster/tree.rs, abd-clam/src/lib.rs, abd-clam/tests/test_tree.rs
This method is primarily for David to use for visualizations.
TODO:
=> Added method to Tree to get a cluster by its offset and cardinality

.bumpversion.cfg, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/cakes/mod.rs, abd-clam/src/core/dataset/mod.rs, abd-clam/src/lib.rs
Also added a getter for shards in Cakes.
TODO:
=> Parallelized distance calculations for expensive metrics

.bumpversion.cfg, abd-clam/Cargo.toml, abd-clam/README.md, abd-clam/src/cakes/knn/mod.rs, abd-clam/src/cakes/mod.rs, abd-clam/src/cakes/rnn/mod.rs, abd-clam/src/cakes/search.rs, abd-clam/src/cakes/sharded.rs, abd-clam/src/cakes/singular.rs, abd-clam/src/core/cluster/_cluster.rs, abd-clam/src/core/cluster/tree.rs, abd-clam/src/core/dataset/instance.rs, abd-clam/src/core/dataset/mod.rs, abd-clam/src/core/dataset/vec2d.rs, abd-clam/src/lib.rs, abd-clam/tests/test_cakes.rs
See commit messages for summary of changes.
This update will allow for the super-expensive builds of trees to be saved and reused.
TODO:
=> Added Save/Load methods to Cakes.

.github/workflows/release.yml, .github/workflows/tests.yml, Earthfile
Also, I added the release flag to cargo test in the Earthfile
=> Added ability to publish from the dev branch

CONTRIBUTING.md
Added changes to contribution guidelines to the mono-repo.
=> fixes to contribution guidelines

CONTRIBUTING.md
Added a section to contributing.md for windows users
=> Windows dev setup

CONTRIBUTING.md
Incorporated some of Carl's suggestions.
=> docs: incorporated review from Carl

Earthfile, crates/SyMaGen/README.md, crates/abd-clam/benches/genomic.rs, crates/abd-clam/benches/knn-search.rs, crates/abd-clam/benches/knn-vs-rnn.rs, crates/abd-clam/benches/rnn-search.rs, crates/abd-clam/src/cakes/knn/mod.rs, crates/abd-clam/src/cakes/search.rs, crates/abd-clam/src/cakes/sharded.rs, crates/abd-clam/src/chaoda/graph/_graph.rs, crates/abd-clam/src/chaoda/graph/criteria.rs, crates/abd-clam/src/utils.rs, crates/abd-clam/tests/test_graph_scorers.rs, crates/abd-clam/tests/utils.rs, crates/distances/src/number/_number.rs, crates/distances/src/number/_variants.rs, crates/distances/src/simd/macros.rs, crates/distances/src/simd/mod.rs, crates/distances/tests/test_sets.rs
This PR:
- Fixes all clippy lints that I find reasonable
- Ignores clippy lints that I find unreasonable
- Updates the earthfile because `rye` changed the link to install the tool
=> Fixed all lints
